language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install redis-server
install: pip install -r requirements.txt
script: python dwarf/manage.py test
